### ISSUE TITLE
Doesn't print report properly on Alpine Linux

### ISSUE THREAD

**Issue by andreiborisov** [jorgebucaran/fishtape#49]
Similar to https://github.com/jorgebucaran/fisher/issues/565, Fishtape doesn't work properly with BusyBox `awk`.

Actual testing seems to work just fine, however, reporting is not correct.

On macOS:

```console
$ fishtape test/*.test.fish
TAP version 13
ok 1 print path for a standalone script
ok 2 print path for a Fisher package
ok 3 print path for a manually installed function

1..3
# pass 3
# ok
```

But on Alpine Linux
```console
$ fishtape test/*.test.fish
TAP version 13
0 print path for a standalone script
1 print path for a Fisher package
2 print path for a manually installed function

1..
# pass 0
# ok
```

Any idea what might be a problem judging by the output?

**Comment by jorgebucaran** [comment]
@andreiborisov Possibly in [this section](https://github.com/jorgebucaran/fishtape/blob/fef3395070a0e47c78f1b4574fa978aa99b8076e/fishtape.fish#L132-L172), specifically [here](https://github.com/jorgebucaran/fishtape/blob/fef3395070a0e47c78f1b4574fa978aa99b8076e/fishtape.fish#L140-L141), and [here](https://github.com/jorgebucaran/fishtape/blob/fef3395070a0e47c78f1b4574fa978aa99b8076e/fishtape.fish#L163).

Maybe we just need to wrap some stuff around (), so instead of:

```awk
 ? mesg : sub(/ok/, "ok " ++total, batch[$1 i])\
 ? batch[$1 i] ((error = batch[$1 i "error"]) && ++failed ? "\n" error : "") : ""
```

...this:

```awk
 ? mesg : sub(/ok/, "ok " (++total), batch[$1 i])\
 ? batch[$1 i] ((error = batch[$1 i "error"]) && (++failed) ? "\n" error : "") : ""
```

Could you try that out?

**Comment by andreiborisov** [comment]
Thanks! The cause was just nearby your suggestion.
